FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ARG GOOGLE_API_KEY
ARG LANGFUSE_HOST
ARG LANGFUSE_PUBLIC_KEY
ARG LANGFUSE_SECRET_KEY
ARG PROJECT_ID
ARG DATA_STORE_ID

ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV LANGFUSE_HOST=$LANGFUSE_HOST
ENV LANGFUSE_PUBLIC_KEY=$LANGFUSE_PUBLIC_KEY
ENV LANGFUSE_SECRET_KEY=$LANGFUSE_SECRET_KEY
ENV PROJECT_ID=$PROJECT_ID
ENV DATA_STORE_ID=$DATA_STORE_ID
ENV environment=production

COPY . .

CMD ["python3", "run.py"]