GET http://localhost:5000/tasks
Accept: application/json

###
POST http://localhost:5000/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE0MzRmMzFkN2Y3NWRiN2QyZjQ0YjgxZDg1MjMwZWQxN2ZlNTk3MzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2EtemVubi1haS1oYWNrYXRob24iLCJhdWQiOiJjYS16ZW5uLWFpLWhhY2thdGhvbiIsImF1dGhfdGltZSI6MTczODY2NDg3NiwidXNlcl9pZCI6IkJRUGtQeTI2SWxURW5temhRR3NWMXJGS3pjOTMiLCJzdWIiOiJCUVBrUHkyNklsVEVubXpoUUdzVjFyRkt6YzkzIiwiaWF0IjoxNzM4NjY0ODc2LCJleHAiOjE3Mzg2Njg0NzYsImVtYWlsIjoidGF0YUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0YXRhQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.RF80nGRDl1cMo5OHcNH-TAQIJ4c8uIOqEdu-Je1cAGZEp6I-xuasn98_ksPPjxmzZKs5_80sVBtPPnjQOU1MFEL_5XwcwyX8O4uxOyYu2sG0IsAz3EgOymVqG9lDAYTF0s-SfO0QFV27o7TgSmiLSTAf3HdLffC1cmpm_7j7AIePxs_eNsUhAtbJvdDC-AhWTRf9DvHKfnGfMlTM9BVdilAd9rMaNX5VT26_TFKfFZKjd_C42cbZbBz_gPtk-PMwUUf9qLVVlnTsAHLkze6nvPoxpLZQeav3Yil1dKpyjRFxu-eEkZhfBcmeNa_2Xo1-yRmgwY4M3VkiUVLwpIXxAg

{
  "message": "1. 週3かいジムに通ってます。 2. 特に気にせず食事してます。3. 睡眠時間は6時間です。"
}
###
GET http://localhost:5000/chats?pages=3

###

###
POST http://127.0.0.1:5000/users/info
Content-Type: application/json
Authorization: Bearer

{
  "name": "なかむら",
  "email": "nakamura.sota@cloud-ace.jp",
  "gender": "男",
  "birthday": "1998-07-31",
  "height": 164,
  "weight": 60,
  "goals": [
    "3ヶ月以内に５キロ痩せる",
    "体脂肪率を標準値以下にする"
  ]
}

###
### GET request to example server
GET http://127.0.0.1:5000/users/nakanakatest/info

###
