GET http://localhost:5000/tasks
Accept: application/json

###
POST http://localhost:5000/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE0MzRmMzFkN2Y3NWRiN2QyZjQ0YjgxZDg1MjMwZWQxN2ZlNTk3MzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2EtemVubi1haS1oYWNrYXRob24iLCJhdWQiOiJjYS16ZW5uLWFpLWhhY2thdGhvbiIsImF1dGhfdGltZSI6MTczODQ4NjQyOSwidXNlcl9pZCI6Imo2VTQyQjF2YTVha1NSNXhSRzFSdHFqV1drdjEiLCJzdWIiOiJqNlU0MkIxdmE1YWtTUjV4UkcxUnRxaldXa3YxIiwiaWF0IjoxNzM4NDg2NDI5LCJleHAiOjE3Mzg0OTAwMjksImVtYWlsIjoic2FrYW1vdG8ua2Vpc3VrZUBjbG91ZC1hY2UuanAiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2FrYW1vdG8ua2Vpc3VrZUBjbG91ZC1hY2UuanAiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.hpG52kIFILpB3pEIcL4WVjQRpwqYsXvZaIA4rRQregGEdp2IpHvIPALQ_Hv94gR_NI8fnYbGXZJMvQWyCcHjnhcyXuJNZD5_6kLOGcHuABtcyJ8c3eFEuvyVTEPQ-Pw15qr9zSkx0x-irVL5kzHX17BqE2QKSQgrg4A4Cba5tTAhRDqtsIG8627keq0uxSuNa4YE5kL825Vf2ACICKMIyKkdc8wtIAlZV_mHJ35Sgp6cp7JpGU4IpXJ_2GZGFk6t2SzH4TnNxHduWfi33y-nqMgpjZuUYtkRxa6WTJEw9yVypqeMFuw8SmfQG3ojQodpR8_oqwrzbmbFcFgAbsRRzw

{
  "message": "スイカの栄養価を教えて"
}
###
GET http://localhost:5000/chats?pages=3

###

###
POST http://127.0.0.1:5000/users/info
Content-Type: application/json
Authorization: Bearer

{
  "name": "なかむら",
  "email": "nakamura.sota@cloud-ace.jp",
  "gender": "男",
  "birthday": "1998-07-31",
  "height": 164,
  "weight": 60,
  "goals": [
    "3ヶ月以内に５キロ痩せる",
    "体脂肪率を標準値以下にする"
  ]
}

###
### GET request to example server
GET http://127.0.0.1:5000/users/nakanakatest/info

###
